### ISSUE TITLE
[Kubernetes,Gateway]: AskTimeoutException: Ask timed out on [Actor[...]] after [25000 ms]. Message of type [akka.cluster.ddata.Replicator$Update]

### ISSUE THREAD

**Issue by Altair-Bueno** [eclipse-ditto/ditto#1649]
### Description

Due to a node crash on my Kubernetes cluster, some pods from Ditto were restarted. These included the NGINX proxy, Ditto Gateway and Ditto Policies. However, NGINX refused to start (init state).

Gateway shows multiple entries with the following contents:

```text
2023-06-08 11:39:08,649 ERROR [] o.e.d.i.u.p.a.SubUpdater akka://ditto-cluster/user/policy-announcement-aware-sub-supervisor/subUpdater2 - Failure updating Ditto pub/sub subscription - trying again next clock tick
java.util.concurrent.CompletionException: akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ditto-cluster/user/policy-announcement-aware-replicator#1986903194]] after [25000 ms]. Message of type [akka.cluster.ddata.Replicator$Update]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:335)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:730)
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:479)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:365)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:314)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:318)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

From my basic understanding on how Akka works, I would say something is wrong on Ditto Policies. Logs from Ditto policies show the following warning messages:

```text
WARN  [] a.r.a.Association Association(akka://ditto-cluster) - Outbound message stream to [akka://ditto-cluster@10.10.34.68:2551] failed. Restarting it. akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://ditto-cluster@10.10.34.68:2551] did not complete within 20000 ms
```

I looked up the `10.10.34.68` IPv4 address using the following command. No pods/services were found within my cluster:

```text
{ kubectl get pods -A -oyaml && kubectl get services -A -oyaml } | grep 10.10.34.68
```

### Hypothesis

1. Akka cluster operated as expected before node failure
2. After node failure K8s re-scheduled pods as stated by their ReplicaSet
3. Akka did not pick up with K8s and used an old cluster IP address

Because that IP address is no longer in use, components were unable to communicate

### Current solution

Restart Ditto

```sh
kubectl rollout restart deployment ditto-gateway ditto-connectivity ditto-policies ditto-things ditto-thingssearch
```

### Expected solution

Ditto should be resilient to these kind of failures. Akka cluster should keep up with Kubernetes scheduling

### Additional information

- Kubernetes: Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
- Helm chart version: 3.1.4

### Probably related

- [Cluster bootstrap based on kubernetes-api discovery does not work](https://github.com/akka/akka-management/issues/236)
- [Cluster bootstrap with DNS does not work when akka management host is a host rather than IP](https://github.com/akka/akka-management/issues/187)

**Comment by thjaeckle** [comment]
Seems like something network related in the k8s cluster.
That's difficult to diagnose now from the "outside" ..

Did you find something out yourself by now?

**Comment by Altair-Bueno** [comment]
Hello Thomas. We spent some time debugging our K8s networks. We also deployed Ditto on our K3s test cluster. It is a single node with a much newer Kubernetes version.

```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.7+k3s1", GitCommit:"f7c20e237d0ad0eae83c1ce60d490da70dbddc0e", GitTreeState:"clean", BuildDate:"2023-03-10T22:16:07Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

## Our findings

### Prometheus metrics

We checked the Prometheus metrics to find out what was happening. We made sure the `global.prometheus.enabled` key was set to `true` on the Helm chart. My Prometheus tried to scrape metrics, but was unable to do so. All ditto pods responded with the same error messages:

```
Get "http://<addr>/": context deadline exceeded
``` 

Our K3s cluster was having similar issues, but the error message was `connection refused` instead.

### Network troubleshooting

We launched a [dnsutils pod](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) for troubleshooting and explored the network with the usual tools:

#### Scraping Prometheus metrics myself using cURL

```sh
# Obtaining the IP address
kubectl get <pod> -oyaml
curl http://<ip>:9095/ -v
```

- dnsutil on K8s: TCP handshake never succeeds. Timeout
- dnsutil on K3s: Connection refused
- Within same the container (loopback address): Works as expected. Metrics are returned

#### Ping

All packages sent from dnsutils were lost both on K3s and K8s.

#### Traceroute

- dnsutil on K8s: Address is unreachable. It just keeps sending packages that get lost

```sh
traceroute to 10.10.34.163 (10.10.34.163), 30 hops max, 60 byte packets
 1  192.168.43.233 (192.168.43.233)  0.069 ms  0.024 ms  0.020 ms
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  * * *
...
```

- dnsutil on K3s: Only one jump. The `10.42.0.1` address is neither a service nor a pod of the cluster. Probably a virtual gateway or kube-proxy.

```sh
# traceroute 10.42.0.140
traceroute to 10.42.0.140 (10.42.0.140), 30 hops max, 60 byte packets
 1  10.42.0.1 (10.42.0.1)  0.246 ms  0.013 ms  0.012 ms
```


## Hypothesis

I've noticed that Ditto pods are the only ones to deploy `networkpolicies.networking.k8s.io` objects on my cluster. They are also the only ones with this kind of networking issues. Could those objects misconfigured? I've never seen this objects before, and frankly I have no idea on how they work. 

We also deployed Ditto with Docker compose, and it appears to be working as expected (fingers crossed). However, we would like to use Ditto within K8s. Could the Helm chart be faulty?

From my understanding, the Docker compose version uses a shared DNS name for discovery while the Kubernetes version is using Networking policies with the Akka cluster adapter. Could it be possible to leverage CoreDNS instead inside Kubernetes?


<details>

<summary>
kubectl get networkpolicies.networking.k8s.io -oyaml
</summary>


```yaml
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      meta.helm.sh/release-name: prueba-ditto
      meta.helm.sh/release-namespace: pruebasot
    creationTimestamp: "2023-06-09T10:51:40Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: prueba-ditto
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ditto-connectivity
      app.kubernetes.io/version: 3.1.2
      helm.sh/chart: ditto-3.1.4
    name: prueba-ditto-connectivity
    namespace: pruebasot
    resourceVersion: "208865624"
    uid: 76b4d154-8db3-42a1-a602-99bdabd2a5a7
  spec:
    egress:
    - {}
    ingress:
    - from:
      - podSelector:
          matchLabels:
            actorSystemName: ditto-cluster
      ports:
      - port: 2551
        protocol: TCP
      - port: 8558
        protocol: TCP
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: prueba-ditto
        app.kubernetes.io/name: ditto-connectivity
    policyTypes:
    - Ingress
    - Egress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      meta.helm.sh/release-name: prueba-ditto
      meta.helm.sh/release-namespace: pruebasot
    creationTimestamp: "2023-06-09T10:51:40Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: prueba-ditto
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ditto-gateway
      app.kubernetes.io/version: 3.1.2
      helm.sh/chart: ditto-3.1.4
    name: prueba-ditto-gateway
    namespace: pruebasot
    resourceVersion: "208865627"
    uid: 03c6f5a0-c271-4595-8991-fa63a55935b7
  spec:
    egress:
    - {}
    ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: prueba-ditto
            app.kubernetes.io/name: ditto-nginx
      ports:
      - port: http
        protocol: TCP
    - from:
      - podSelector:
          matchLabels:
            actorSystemName: ditto-cluster
      ports:
      - port: 2551
        protocol: TCP
      - port: 8558
        protocol: TCP
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: prueba-ditto
        app.kubernetes.io/name: ditto-gateway
    policyTypes:
    - Ingress
    - Egress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      meta.helm.sh/release-name: prueba-ditto
      meta.helm.sh/release-namespace: pruebasot
    creationTimestamp: "2023-06-09T10:51:40Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: prueba-ditto
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ditto-nginx
      app.kubernetes.io/version: 3.1.2
      helm.sh/chart: ditto-3.1.4
    name: prueba-ditto-nginx
    namespace: pruebasot
    resourceVersion: "208865625"
    uid: 90d5948a-bcc6-4282-bf5a-bdbf42fcc042
  spec:
    ingress:
    - ports:
      - port: 8080
        protocol: TCP
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: prueba-ditto
        app.kubernetes.io/name: ditto-nginx
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      meta.helm.sh/release-name: prueba-ditto
      meta.helm.sh/release-namespace: pruebasot
    creationTimestamp: "2023-06-09T10:51:40Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: prueba-ditto
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ditto-policies
      app.kubernetes.io/version: 3.1.2
      helm.sh/chart: ditto-3.1.4
    name: prueba-ditto-policies
    namespace: pruebasot
    resourceVersion: "208865626"
    uid: ece338b5-2542-4c91-9d61-56d2cb380c0b
  spec:
    egress:
    - {}
    ingress:
    - from:
      - podSelector:
          matchLabels:
            actorSystemName: ditto-cluster
      ports:
      - port: 2551
        protocol: TCP
      - port: 8558
        protocol: TCP
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: prueba-ditto
        app.kubernetes.io/name: ditto-policies
    policyTypes:
    - Ingress
    - Egress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      meta.helm.sh/release-name: prueba-ditto
      meta.helm.sh/release-namespace: pruebasot
    creationTimestamp: "2023-06-09T10:51:40Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: prueba-ditto
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ditto-swaggerui
      app.kubernetes.io/version: 3.1.2
      helm.sh/chart: ditto-3.1.4
    name: prueba-ditto-swaggerui
    namespace: pruebasot
    resourceVersion: "208865629"
    uid: 7543a7f6-17e2-4799-a514-efea998440fd
  spec:
    ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: prueba-ditto
            app.kubernetes.io/name: ditto-nginx
      ports:
      - port: 8080
        protocol: TCP
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: prueba-ditto
        app.kubernetes.io/name: ditto-swaggerui
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      meta.helm.sh/release-name: prueba-ditto
      meta.helm.sh/release-namespace: pruebasot
    creationTimestamp: "2023-06-09T10:51:40Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: prueba-ditto
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ditto-things
      app.kubernetes.io/version: 3.1.2
      helm.sh/chart: ditto-3.1.4
    name: prueba-ditto-things
    namespace: pruebasot
    resourceVersion: "208865628"
    uid: 09c3a802-027e-404f-bb08-55970e937afd
  spec:
    egress:
    - {}
    ingress:
    - from:
      - podSelector:
          matchLabels:
            actorSystemName: ditto-cluster
      ports:
      - port: 2551
        protocol: TCP
      - port: 8558
        protocol: TCP
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: prueba-ditto
        app.kubernetes.io/name: ditto-things
    policyTypes:
    - Ingress
    - Egress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      meta.helm.sh/release-name: prueba-ditto
      meta.helm.sh/release-namespace: pruebasot
    creationTimestamp: "2023-06-09T10:51:40Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: prueba-ditto
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ditto-thingssearch
      app.kubernetes.io/version: 3.1.2
      helm.sh/chart: ditto-3.1.4
    name: prueba-ditto-thingssearch
    namespace: pruebasot
    resourceVersion: "208865630"
    uid: 4d682783-d764-4421-8136-c51045b9fa9c
  spec:
    egress:
    - {}
    ingress:
    - from:
      - podSelector:
          matchLabels:
            actorSystemName: ditto-cluster
      ports:
      - port: 2551
        protocol: TCP
      - port: 8558
        protocol: TCP
    podSelector:
      matchLabels:
        app.kubernetes.io/instance: prueba-ditto
        app.kubernetes.io/name: ditto-thingssearch
    policyTypes:
    - Ingress
    - Egress
kind: List
metadata:
  resourceVersion: ""

```


</details>

**Comment by Altair-Bueno** [comment]
After my last comment, we have disabled Ditto's network policies. This can be archived with the following values on the helm chart:

```yml
connectivity:
  networkPolicy:
    enabled: false
gateway:
  networkPolicy:
    enabled: false
policies:
  networkPolicy:
    enabled: false
things:
  networkPolicy:
    enabled: false
thingsSearch:
  networkPolicy:
    enabled: false
```

This solves the AskTimeoutExceptions we were experiencing, as well as allowing our Prometheus to scrape metrics. We didn't experience any issues related to networking, even with pod failure.

I also took some time to learn the basics of `networkpolicies.networking.k8s.io` objects. Those objects generated by the helm chart look fine to me, except they do not allow for either ingress or egress from the Kubernetes control panel. From my understanding, Akka listens for events from the control panel and heals the cluster based on what pods are currently available. Could that be the reason why Akka didn't re-stablish connection successfully, and instead used an old pod address?

**Comment by thjaeckle** [comment]
> I also took some time to learn the basics of networkpolicies.networking.k8s.io objects. Those objects generated by the helm chart look fine to me, except they do not allow for either ingress or egress from the Kubernetes control panel. From my understanding, Akka listens for events from the control panel and heals the cluster based on what pods are currently available. Could that be the reason why Akka didn't re-stablish connection successfully, and instead used an old ip address?

Hm, very good finding.
To be honest, I never looked deeply into the network policies, the original helm chart was contributed to Ditto by someone with probably no Akka knowledge.

I see it as optional, however with your finding it is even dangerous to use.

Will also have a closer look into it and probably remove it from the chart.
